In [4]:
import torch

In [5]:
print(f"Torch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"CUDA version: {torch.version.cuda}")

Torch version: 2.5.0+cu124
CUDA available: True
CUDA version: 12.4


# Tensors

Tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.

### Scalar (0D Tensor)

In [7]:
scalar = torch.tensor(3.14159)

scalar

tensor(3.1416)

In [10]:
scalar.ndim

0

In [13]:
scalar.item()

3.141590118408203

### Vector (1D Tensor)

In [15]:
vector = torch.tensor([1, 2, 3, 4, 5])

vector

tensor([1, 2, 3, 4, 5])

In [16]:
vector.ndim

1

In [17]:
vector.shape

torch.Size([5])

### Matrix (2D Tensor)

In [19]:
matrix = torch.tensor([[1, 2], [4, 5], [7, 8]])

matrix

tensor([[1, 2],
        [4, 5],
        [7, 8]])

In [20]:
matrix.ndim

2

In [21]:
matrix.shape

torch.Size([3, 2])

### Tensor (3D or higher)

In [23]:
tensor = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

tensor

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [24]:
tensor.ndim

3

In [25]:
tensor.shape

torch.Size([2, 2, 2])

#### Random Tensors

In [31]:
random_tensor = torch.rand(3, 4)

random_tensor

tensor([[0.8017, 0.7721, 0.6605, 0.0147],
        [0.8074, 0.2784, 0.6312, 0.5043],
        [0.8512, 0.1006, 0.9566, 0.5493]])

In [32]:
random_tensor.shape

torch.Size([3, 4])

In [33]:
random_tensor = torch.rand(2, 2, 2)

random_tensor

tensor([[[0.1274, 0.8073],
         [0.8941, 0.9559]],

        [[0.9163, 0.1142],
         [0.4736, 0.0229]]])

In [34]:
random_tensor.shape

torch.Size([2, 2, 2])

In [37]:
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # 3 channels, 224x224 image

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

#### Zeros and Ones Tensors

In [40]:
zeros_tensor = torch.zeros(size=(3, 4))

zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [42]:
zeros_tensor.dtype

torch.float32

In [41]:
ones_tensor = torch.ones(size=(3, 4))

ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [43]:
ones_tensor.dtype

torch.float32

#### Range of Tensors and Tensors-like

In [46]:
five_numbers = torch.arange(start=0, end=10, step=2)

five_numbers

tensor([0, 2, 4, 6, 8])

In [47]:
five_zeros = torch.zeros_like(five_numbers)

five_zeros

tensor([0, 0, 0, 0, 0])

### Tensors Data Types

In [49]:
int_64_tensor = torch.tensor([1, 2, 3], dtype=None)

int_64_tensor.dtype

torch.int64

In [51]:
int_8_tensor = torch.tensor([1, 2, 3], dtype=torch.int8)

int_8_tensor.dtype

torch.int8

In [50]:
float_32_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=None)

float_32_tensor.dtype

torch.float32

In [52]:
float_16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)

float_16_tensor.dtype

torch.float16

In [53]:
float_32_tensor = torch.tensor(
    [1.0, 2.0, 3.0],
    dtype=None,         # Float32
    device=None,        # CPU
    requires_grad=False # no gradient tracking
)

float_32_tensor.dtype

torch.float32

In [55]:
int_64_tensor = float_32_tensor.to(dtype=torch.int64)

int_64_tensor

tensor([1, 2, 3])

In [57]:
result = float_32_tensor + int_64_tensor

result, result.dtype

(tensor([2., 4., 6.]), torch.float32)

### Getting Information from Tensors

In [60]:
some_tensor = torch.rand(3, 4)

some_tensor

tensor([[0.4651, 0.4062, 0.3348, 0.1619],
        [0.5076, 0.6795, 0.6298, 0.5304],
        [0.2172, 0.2306, 0.0991, 0.9163]])

In [61]:
some_tensor.dtype

torch.float32

In [62]:
some_tensor.shape

torch.Size([3, 4])

In [63]:
some_tensor.device

device(type='cpu')

### Tensor Operations

In [66]:
tensor = torch.tensor([1, 2, 3])

tensor

tensor([1, 2, 3])

In [70]:
tensor + 10, torch.add(tensor, 10)

(tensor([11, 12, 13]), tensor([11, 12, 13]))

In [71]:
tensor * 10, torch.mul(tensor, 10)

(tensor([10, 20, 30]), tensor([10, 20, 30]))

In [72]:
tensor - 10, torch.sub(tensor, 10)

(tensor([-9, -8, -7]), tensor([-9, -8, -7]))

In [73]:
tensor / 10, torch.div(tensor, 10)

(tensor([0.1000, 0.2000, 0.3000]), tensor([0.1000, 0.2000, 0.3000]))

In [77]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

print(f"Addition: {tensor1 + tensor2}")
print(f"Subtraction: {tensor1 - tensor2}")
print(f"Multiplication: {tensor1 * tensor2}")
print(f"Division: {tensor1 / tensor2}")

Addition: tensor([5, 7, 9])
Subtraction: tensor([-3, -3, -3])
Multiplication: tensor([ 4, 10, 18])
Division: tensor([0.2500, 0.4000, 0.5000])


In [78]:
torch.matmul(tensor1, tensor2)

tensor(32)

In [83]:
tensor3 = torch.tensor([[4], [5], [6]])

tensor3

tensor([[4],
        [5],
        [6]])

In [82]:
torch.matmul(tensor1, tensor3)

tensor([32])

In [84]:
%%time

value = 0

for i in range(len(tensor1)):
    value += tensor1[i] * tensor2[i]

value

CPU times: user 2.41 ms, sys: 0 ns, total: 2.41 ms
Wall time: 4.63 ms


tensor(32)

In [85]:
%%time

torch.dot(tensor1, tensor2)

CPU times: user 132 μs, sys: 66 μs, total: 198 μs
Wall time: 132 μs


tensor(32)

In [86]:
matrix1 = torch.tensor([[1, 2], [3, 4]])
matrix2 = torch.tensor([[5, 6], [7, 8]])

torch.matmul(matrix1, matrix2)

tensor([[19, 22],
        [43, 50]])

In [89]:
torch.mm(matrix1, matrix2)

tensor([[19, 22],
        [43, 50]])

In [87]:
matrix1 @ matrix2

tensor([[19, 22],
        [43, 50]])

In [88]:
matrix1 * matrix2

tensor([[ 5, 12],
        [21, 32]])

In [91]:
matrix1 = torch.tensor([[1, 2], [3, 4], [5, 6]])
matrix2 = torch.tensor([[7, 8], [9, 10], [11, 12]])

# torch.mm(matrix1, matrix2) -> Error because of shape mismatch (3x2 * 3x2)
torch.mm(matrix1, matrix2.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])