In [1]:
import torch

import pandas as pd

from torch import nn
from torchvision import datasets
from torch.utils.data import DataLoader
from torchvision.transforms import ToTensor

import matplotlib.pyplot as plt

from timeit import default_timer as timer
from tqdm import tqdm

In [10]:
conv_layer = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=3,
    stride=1,
    padding=1
)

conv_layer

Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))

In [11]:
conv_layer(torch.rand(1, 1, 5, 5)).shape

torch.Size([1, 1, 5, 5])

In [12]:
pooling_layer = nn.MaxPool2d(kernel_size=2)

pooling_layer(torch.rand(1, 1, 5, 5)).shape

torch.Size([1, 1, 2, 2])

In [ ]:
import torch
import torch.nn as nn

# Criando uma camada Conv2d
conv = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=3,
    bias=False,
    padding=1
)

# Definindo um kernel personalizado (3x3)
custom_kernel = torch.tensor(
    [[ 0.0, -1.0,  0.0],
     [-1.0,  5.0, -1.0],
     [ 0.0, -1.0,  0.0]],
     dtype=torch.float32
)

# Atribuindo o kernel à camada Conv2d
# O peso precisa ter o formato (out_channels, in_channels, kernel_size, kernel_size)
conv.weight.data = custom_kernel.unsqueeze(0).unsqueeze(0)

# Definindo a entrada com os valores da imagem (5x5)
input_tensor = torch.tensor(
    [[
        [60, 113, 56, 139, 85],
        [73, 121, 54, 84, 128],
        [131, 99, 70, 129, 127],
        [80, 57, 115, 69, 134],
        [104, 126, 123, 95, 130],
    ]], dtype=torch.float32
).unsqueeze(0)  # Adiciona batch dimension

# Aplicando a convolução
output = conv(input_tensor)

# Resultado
print("Input:")
print(input_tensor.squeeze().numpy())

print("\nKernel:")
print(custom_kernel.numpy())

print("\nOutput:")
print(output.squeeze().detach().numpy())



Input:
[[ 60. 113.  56. 139.  85.]
 [ 73. 121.  54.  84. 128.]
 [131.  99.  70. 129. 127.]
 [ 80.  57. 115.  69. 134.]
 [104. 126. 123.  95. 130.]]

Kernel:
[[ 0. -1.  0.]
 [-1.  5. -1.]
 [ 0. -1.  0.]]

Output:
[[ 114.  328.  -26.  470.  158.]
 [  53.  266.  -61.  -30.  344.]
 [ 403.  116.  -47.  295.  244.]
 [ 108. -135.  256. -128.  344.]
 [ 314.  346.  279.  153.  421.]]


In [17]:
import torch
import torch.nn as nn

# Matriz de entrada (4x4)
input_tensor = torch.tensor(
    [[7, 3, 5, 2],
     [8, 7, 1, 6],
     [4, 9, 3, 9],
     [0, 8, 4, 5]],
    dtype=torch.float32
).unsqueeze(0).unsqueeze(0)  # Adiciona dimensões de batch e canais (1x1x4x4)

# Definir o MaxPooling com kernel 2x2, stride 2 e sem padding
maxpool = nn.MaxPool2d(kernel_size=2, stride=2)

# Aplicar o MaxPooling
output = maxpool(input_tensor)

print("Matriz de entrada:")
print(input_tensor.squeeze().numpy())

print("\nMatriz após MaxPooling:")
print(output.squeeze().numpy())


Matriz de entrada:
[[7. 3. 5. 2.]
 [8. 7. 1. 6.]
 [4. 9. 3. 9.]
 [0. 8. 4. 5.]]

Matriz após MaxPooling:
[[8. 6.]
 [9. 9.]]
